--- 
# https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service  
kind: Service 
apiVersion: v1 
metadata: 
  name: web-app1o 
spec: 
  type: NodePort
  ports: 
  - targetPort: 5000
    port: 5000
    nodePort: 31008
  selector:
    app: webapp16      
  type: LoadBalancer  
 
